class: 1
interval: 20
routines:
  profile:
    condition:
      psi:
        type: 0
        some:
            - -1
            - -1
            - 0
    content:
      cpu_profile: null
start: profile
