name: hermes
base: core20
version: '1.0'
summary: Time-series profiling tool
description: |
  A time-series profiling tool for analyzing system performance issues 
  from different dimensions.
grade: devel
confinement: classic
apps:
  collector:
    command: usr/sbin/collector --config_dir $SNAP_USER_COMMON/config
  parser:
    command: usr/sbin/parser  --output_dir $SNAP_USER_COMMON/view
  webserver:
    command: usr/sbin/webserver --frontend_dir $SNAP_USER_COMMON/frontend --view_dir $SNAP_USER_COMMON/view
parts:
  hermes:
    source: https://github.com/canonical/hermes.git
    plugin: make
